apiVersion: apps/v1
kind: Deployment
metadata:
  name: isis-4
spec:
  selector:
    matchLabels:
      app: isis-4-label
  replicas: 3
  template:
    metadata:
      labels:
        app: isis-4-label
    spec:
      containers:
        - name: isis4-web
          image: alexpotagashev/myrepo:isis2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "1000Mi"
            limits:
              cpu: "100m"
              memory: "2000Mi"
